### ISSUE TITLE
type of input files

### ISSUE THREAD

**Issue by sashulkaSh** [rxn4chemistry/rxnaamapper#2]
Hello! Can you please tell me what format the input data should be in? should I convert fasta format of protein sequences to another?..

**Comment by drugilsberg** [comment]
Hi @sashulkaSh thanks for the interest in our research.
Please check out the example input we provide in the repo: https://github.com/rxn4chemistry/rxnaamapper/tree/main/examples/data-samples.
You should be able to convert you fasta easily for usage with rxnaamapper.

**Comment by sashulkaSh** [comment]
Do I understand correctly that I need to manually translate the amino acid sequence written in literal form into a structural formula? (of course, I saw other of the csv file fields too)

**Comment by sashulkaSh** [comment]
What software would you recommend to use for such conversion?

**Comment by drugilsberg** [comment]
> Do I understand correctly that I need to manually translate the amino acid sequence written in literal form into a structural formula? (of course, I saw other of the csv file fields too)

Hi @sashulkaSh it depends what you want to achieve.

In general for training you just need enzymatic reaction and extend them using AA sequence information. For example, in the [rxnaamapper workshop paper](https://doi.org/10.26434/chemrxiv-2021-m20gg-v2) we used [ECREACT](https://github.com/rxn4chemistry/biocatalysis-model/blob/main/data/ecreact-1.0.csv) from our previous paper and transformed the reaction by replacing the EC number with corresponding sequences from UniProt.

An example using the first entry in the dataset.

The reaction from ECREACT:
```txt
NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)c1.NCCC=O.O|1.2.1.8>>NCCC(=O)O
```

Can be transformed with any AA sequence from UniProt mapping to 1.2.1.8 (https://www.uniprot.org/uniprot/P17444)

```txt
NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)c1.NCCC=O.O|MQFDYIIIGAGSAGNVLATR...TAGYFVANGMPVRAKK>>NCCC(=O)O
```

You can do this with the program you prefer, once the dataset is prepared following the format I linked above (from our example) you can run the training pipeline and create your model.

For inference you can provide a full reaction SMILES for AA or omit the product.
See the example in the README.md for an example of getting the mapping between substrate atoms and AA from the sequence of interest.
