### ISSUE TITLE
Pretrained model 

### ISSUE THREAD

**Issue by saleha1wer** [rxn4chemistry/rxnaamapper#9]
Hi,

Is the pretrained model available somewhere?

**Comment by yvesnana** [comment]
Hi @saleha1wer 

There are no model checkpoints released, but all the steps for retraining the model are available [here](https://github.com/rxn4chemistry/rxnaamapper#train-the-model).
Using the data available on Zenodo ([Dataset of biocatalyzed reactions](https://doi.org/10.5281/zenodo.7530180)) you can recreate the same model from the paper.

Thanks a lot for the interest in our research.

Best,
Yves
